# Generated by Django 3.0.3 on 2020-04-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
