# Generated by Django 3.0.3 on 2020-04-18 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='games/')),
                ('review_int', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_str', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
