# Generated by Django 3.0.3 on 2020-04-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_review_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='developer',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='platform',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='publisher',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sys_requirement',
            field=models.TextField(null=True),
        ),
    ]
